### ISSUE TITLE
[feature request] Integrates with Residence 

### ISSUE THREAD

**Issue by RICE0707** [NaspoDev/Tether#4]

**Comment by NaspoDev** [comment]
Thank you for the suggestion!

I'd love to implement support for Residence, and while they do have a public API, they don't have a public repository for it. Therefore, I'd have to buy the plugin and add it's jar as a local library in the plugin.
Unfortunately, demand isn't high enough at this time to warrant me spending the money on the plugin.

Sorry! :(

**Comment by SrBedrock** [comment]
I think this can be closed now?
From config.yml:
```yml
# Should Tether hook into the following land management plugins?
# (Requires restart upon change).
hooks:
  griefprevention: false
  towny: false
  lands: false
  griefdefender: false
  residence: false
```
